name: Tests
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'website/*'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'website/*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Terraform fmt
        run: |
          make tf-check
      - name: Build
        run: |
          make
      - name: Test pre-requisites
        run: sudo apt-get -y install xsltproc
      - name: Test
        run: |
          make test
